version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres:13.10
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: tests_user
      POSTGRES_PASSWORD: tests_password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build: ./genetictests/
    command: sh -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    depends_on:
      - db
    ports:
      - 8000:8000
