# Generated by Django 4.2.17 on 2024-12-12 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animamal_name', models.CharField(max_length=40)),
                ('species', models.CharField(max_length=40)),
                ('test_date', models.DateField()),
                ('milk_yield', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, 'Минимальное значение 0.0.')])),
                ('health_status', models.CharField(choices=[('good', 'good'), ('poor', 'poor')], max_length=4)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
